auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_concurrent_streams: 200

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 90s
  max_transfer_retries: 1

schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: ${DYNAMODB_PREFIX}
      period: 24h

storage_config:
  # s3
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: s3

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: s3

limits_config:
  enforce_metric_name: false
  reject_old_samples: false
  # reject_old_samples_max_age: 12h

# chunk_store_config:
#   max_look_back_period: 720h

table_manager:
  retention_deletes_enabled: false
  # retention_period: 720h

ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: ${ALERTMANAGER_URL}
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
