version: "3.8"
services:
  agent:
    build: ./agent
    volumes:
      - /usr/local/var/log:/usr/local/var/log
  loki:
    build: ./loki
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/local-config.yaml"]
  promtail:
    build: ./promtail
    ports:
      - "9080:9080"
    volumes:
      - /usr/local/var/log:/usr/local/var/log
    command: ["-config.file=/etc/promtail/config.yml", "-client.url", "http://loki:3100/loki/api/v1/push"]
    depends_on:
      - loki
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      - LOKI_URL=http://loki:3100
    depends_on:
      - promtail
