version: "3.9"
services:
  agent:
    build: ./agent
    volumes:
      - ./ceramic:/logs/ceramic
  alertmanager:
    build: ./alertmanager
    ports:
      - "9093:9093"
    command: ["--config.file=/etc/alertmanager/local-config.yaml", "--cluster.listen-address=", "--log.level=debug"]
  alertmanager-discord:
    build: ./alertmanager-discord
    ports:
      - "9096:9096"
    environment:
      - LISTEN_ADDRESS=0.0.0.0:9096
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - ENV=dev
  loki:
    build: ./loki
    ports:
      - "3100:3100"
    environment:
      - ALERTMANAGER_URL=http://alertmanager:9093
      - DYNAMODB_PREFIX=loki_
    command: ["-config.file=/etc/loki/local-config.yaml", "-config.expand-env=true"]
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
  promtail:
    build: ./promtail
    ports:
      - "9080:9080"
    volumes:
      - ./cas:/logs/cas
      - ./ceramic:/logs/ceramic
    command: ["-config.file=/etc/promtail/local-config.yml", "-client.url", "http://loki:3100/loki/api/v1/push", "-log.level=debug"]
    depends_on:
      - loki
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      - DASHBOARDS_PATH=/etc/grafana/provisioning/dashboards/${DASHBOARD}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - LOKI_URL=http://loki:3100
      - PROMETHEUS_URL=http://prometheus:9090
      - AWS_AUTH_TYPE=keys
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - CLOUDWATCH_METRICS_NAMESPACES=pubsub-dev
    depends_on:
      - promtail
  stats_agent:
    build: ./stats_agent
    ports:
      - "9464:9464"
