version: "3.8"
services:
  agent:
    build: ./agent
    volumes:
      - /usr/local/var/log:/var/log
  loki:
    build: ./loki
    ports:
      - "3100:3100"
  promtail:
    build: ./promtail
    ports:
      - "9080:9080"
    volumes:
      - /usr/local/var/log:/var/log
    depends_on:
      - loki
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - promtail
