version: "3.8"
services:
  agent:
    build: ./agent
    volumes:
      - ./ceramic:/logs/ceramic
  alertmanager:
    build: ./alertmanager
    ports:
      - "9093:9093"
    command: ["--config.file=/etc/alertmanager/local-config.yaml"]
  alertmanager-discord:
    build: ./alertmanager-discord
    ports:
      - "9095:9095"
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
  loki:
    build: ./loki
    ports:
      - "3100:3100"
    environment:
      - DYNAMODB_PREFIX=loki_
    command: ["-config.file=/etc/loki/local-config.yaml", "-config.expand-env=true"]
  promtail:
    build: ./promtail
    ports:
      - "9080:9080"
    volumes:
      - ./cas:/logs/cas
      - ./ceramic:/logs/ceramic
    command: ["-config.file=/etc/promtail/local-config.yml", "-client.url", "http://loki:3100/loki/api/v1/push", "-log.level=debug"]
    depends_on:
      - loki
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      - DASHBOARDS_PATH=/etc/grafana/provisioning/dashboards/${DASHBOARD}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - LOKI_URL=http://loki:3100
      - AWS_AUTH_TYPE=keys
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    depends_on:
      - promtail
