{
 "title": "Node (ELP)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HealthyHostCount ( 1-1-node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-elp-1-1-node/d7bd505e4d96dfbd",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( 1-1-ipfs )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-elp-1-1-ipfs-nd-ex/747b799af0ef1202",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-elp-1-1-ipfs-nd-in/64446e6002e5eb85",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( 1-2-node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-elp-1-2-node/5e8be8c534a40f59",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( 1-2-ipfs )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-elp-1-2-ipfs-nd-ex/152bae923b15d3cb",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-elp-1-2-ipfs-nd-in/25db4ddf635cbda7",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( 1-1-node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ metric }}_{{ stat }} (4096 CPU)",
     "dimensions": { "ClusterName": "ceramic-prod-ex", "ServiceName": "ceramic-elp-1-1-node" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( 1-2-node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ metric }}_{{ stat }} (4096 CPU)",
     "dimensions": { "ClusterName": "ceramic-prod-ex", "ServiceName": "ceramic-elp-1-2-node" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( 1-1-node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ metric }}_{{ stat }} (8192 MiBs)",
     "dimensions": { "ClusterName": "ceramic-prod-ex", "ServiceName": "ceramic-elp-1-1-node" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( 1-2-node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ metric }}_{{ stat }} (8192 MiBs)",
     "dimensions": { "ClusterName": "ceramic-prod-ex", "ServiceName": "ceramic-elp-1-2-node" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( 1-1-ipfs )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ metric }}_{{ stat }} (4096 CPU)",
     "dimensions": { "ClusterName": "ceramic-prod-ex", "ServiceName": "ceramic-elp-1-1-ipfs-nd" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( 1-2-ipfs )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ metric }}_{{ stat }} (4096 CPU)",
     "dimensions": { "ClusterName": "ceramic-prod-ex", "ServiceName": "ceramic-elp-1-2-ipfs-nd" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( 1-1-ipfs )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ metric }}_{{ stat }} (8192 MiBs)",
     "dimensions": { "ClusterName": "ceramic-prod-ex", "ServiceName": "ceramic-elp-1-1-ipfs-nd" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( 1-2-ipfs )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{ metric }}_{{ stat }} (8192 MiBs)",
     "dimensions": { "ClusterName": "ceramic-prod-ex", "ServiceName": "ceramic-elp-1-2-ipfs-nd" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Requests ( 1-1 )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} [$bucket])",
     "legendFormat": "Total requests/$bucket"
    }
   ]
  },
  {
   "title": "Requests ( 1-2 )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} [$bucket])",
     "legendFormat": "Total requests/$bucket"
    }
   ]
  },
  {
   "title": "Responses by Status ( 1-1 )",
   "type": "graph",
   "description": "Responses by status / $bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 200 and status < 300 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 300 and status < 400 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 400 and status < 500 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 500 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Responses by Status ( 1-2 )",
   "type": "graph",
   "description": "Responses by status / $bucket",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 200 and status < 300 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 300 and status < 400 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 400 and status < 500 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 500 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "GET Requests ( 1-1 )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | method=\"GET\" [$bucket]))",
     "legendFormat": "GET requests/$bucket"
    }
   ]
  },
  {
   "title": "GET Requests ( 1-2 )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | method=\"GET\" [$bucket]))",
     "legendFormat": "GET requests/$bucket"
    }
   ]
  },
  {
   "title": "POST Requests ( 1-1 )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | method=\"POST\" [$bucket]))",
     "legendFormat": "POST requests/$bucket"
    }
   ]
  },
  {
   "title": "POST Requests ( 1-2 )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | method=\"POST\" [$bucket]))",
     "legendFormat": "POST requests/$bucket"
    }
   ]
  },
  {
   "title": "Requests per Endpoint ( 1-1 )",
   "type": "graph",
   "description": "Requests per endpoint per $bucket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests per Endpoint ( 1-2 )",
   "type": "graph",
   "description": "Requests per endpoint per $bucket",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Requests per Origin ( 1-1 )",
   "type": "graph",
   "description": "Requests per origin per $bucket, stacked",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ip) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Requests per Origin ( 1-2 )",
   "type": "graph",
   "description": "Requests per origin per $bucket, stacked",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ip) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Requests per Origin per Endpoint ( 1-1 )",
   "type": "graph",
   "description": "Requests per origin per endpoint per $bucket, stacked",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ip, path) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket]))",
     "legendFormat": "{{ ip }}, {{ path }}"
    }
   ]
  },
  {
   "title": "Requests per Origin per Endpoint ( 1-2 )",
   "type": "graph",
   "description": "Requests per origin per endpoint per $bucket, stacked",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ip, path) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket]))",
     "legendFormat": "{{ ip }}, {{ path }}"
    }
   ]
  },
  {
   "title": "# of Unique Origins Active ( 1-1 )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (ip) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "Unique origins / $bucket"
    }
   ]
  },
  {
   "title": "# of Unique Origins Active ( 1-2 )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (ip) (count_over_time({app=\"partners\", job=\"ceramic/http\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/http-access.log\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "Unique origins / $bucket"
    }
   ]
  }
 ]
}