{
 "title": "PubSub",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pubsub_topic", "query": "/ceramic/mainnet" }
  ]
 },
 "panels": [
  {
   "title": "Received in $pubsub_topic ( ceramic-private )",
   "type": "graph",
   "description": "Pubsub messages logged on the Ceramic private node with event `received`",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (event) (count_over_time({app=\"node-private\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | event = \"received\" [1s]))"
    }
   ]
  },
  {
   "title": "Received in $pubsub_topic ( gateway )",
   "type": "graph",
   "description": "Pubsub messages logged on the Ceramic gateway with event `received`",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (event) (count_over_time({app=\"gateway-public\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | event = \"received\" [1s]))"
    }
   ]
  },
  {
   "title": "Received in $pubsub_topic ( elp-1-1 )",
   "type": "graph",
   "description": "Pubsub messages logged on the Ceramic partner nodes with event `received`",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (event) (count_over_time({app=\"partners\", job=\"ceramic/pubsub\", filename=\"/logs/ceramic/external/ceramic-elp-1-1/pubsub.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | event = \"received\" [1s]))",
     "legendFormat": "cohort 1 node 1"
    }
   ]
  },
  {
   "title": "Received in $pubsub_topic ( elp-1-2 )",
   "type": "graph",
   "description": "Pubsub messages logged on the Ceramic partner nodes with event `received`",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (event) (count_over_time({app=\"partners\", job=\"ceramic/pubsub\", filename=\"/logs/ceramic/external/ceramic-elp-1-2/pubsub.log\"} | logfmt | __error__!=\"LogfmtParserErr\" | event = \"received\" [1s]))",
     "legendFormat": "cohort 1 node 2"
    }
   ]
  },
  {
   "title": "Updates in $pubsub_topic",
   "type": "graph",
   "description": "Updates (i.e. message \"typ\" equals 0) stacked",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-private\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=0 [$__interval])) by (job)",
     "legendFormat": "ceramic-private"
    },
    {
     "expr": "sum(count_over_time({app=\"partners\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=0 [$__interval])) by (job)",
     "legendFormat": "elp"
    },
    {
     "expr": "sum(count_over_time({app=\"gateway-public\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=0 [$__interval])) by (job)",
     "legendFormat": "gateway"
    }
   ]
  },
  {
   "title": "Queries in $pubsub_topic",
   "type": "graph",
   "description": "Queries (i.e. message \"typ\" equals 1 and event is received) stacked",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-private\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=1 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "ceramic-private"
    },
    {
     "expr": "sum(count_over_time({app=\"partners\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=1 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "elp"
    },
    {
     "expr": "sum(count_over_time({app=\"gateway-public\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=1 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "gateway"
    }
   ]
  },
  {
   "title": "Responses in $pubsub_topic",
   "type": "graph",
   "description": "Queries (i.e. message \"typ\" equals 2 and event is published) stacked",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-private\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=2 and event=\"published\" [$__interval])) by (job)",
     "legendFormat": "responses"
    },
    {
     "expr": "sum(count_over_time({app=\"partners\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=2 and event=\"published\" [$__interval])) by (job)",
     "legendFormat": "responses"
    },
    {
     "expr": "sum(count_over_time({app=\"gateway-public\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=2 and event=\"published\" [$__interval])) by (job)",
     "legendFormat": "responses"
    }
   ]
  }
 ]
}