{
 "title": "Anchor Service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "All GET Requests per Second",
   "type": "graph",
   "description": "Number of GET requests each second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cas/access\"} |= \"method=GET\" [1s])",
     "legendFormat": "requests per second"
    }
   ]
  },
  {
   "title": "All POST Requests per Second",
   "type": "graph",
   "description": "Number of POST requests each second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cas/access\"} |= \"method=POST\" [1s])",
     "legendFormat": "requests per second"
    }
   ]
  },
  {
   "title": "/api/v0/requests GET Requests per Second",
   "type": "graph",
   "description": "Number of GET requests to /api/v0/requests each second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/api/v0/requests\" | logfmt | method=\"GET\" and status >= 200 and status < 300 [1s]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/api/v0/requests\" | logfmt | method=\"GET\" and status >= 200 and status < 300 [1s]))",
     "legendFormat": "{{ ip }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/api/v0/requests\" | logfmt | method=\"GET\" and status >= 400 and status < 500 [1s]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/api/v0/requests\" | logfmt | method=\"GET\" and status >= 400 and status < 500 [1s]))",
     "legendFormat": "{{ ip }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/api/v0/requests\" | logfmt | method=\"GET\" and status >= 500 [1s]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/api/v0/requests\" | logfmt | method=\"GET\" and status >= 500 [1s]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "/api/v0/requests POST Requests per Second",
   "type": "graph",
   "description": "Number of POST requests to /api/v0/requests each second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/requests\" | logfmt | method=\"POST\" and status >= 200 and status < 300 [1s]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/requests\" | logfmt | method=\"POST\" and status >= 200 and status < 300 [1s]))",
     "legendFormat": "{{ ip }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/requests\" | logfmt | method=\"POST\" and status >= 400 and status < 500 [1s]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/requests\" | logfmt | method=\"POST\" and status >= 400 and status < 500 [1s]))",
     "legendFormat": "{{ ip }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/requests\" | logfmt | method=\"POST\" and status >= 500 [1s]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/requests\" | logfmt | method=\"POST\" and status >= 500 [1s]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "ETH Balance in Gwei",
   "type": "graph",
   "description": "Ethereum balance of anchor service wallet in gwei",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "gwei" }
   ],
   "targets": [
    {
     "expr": "sum_over_time({job=\"cas/metrics\"} |= \"walletBalance\" | logfmt | unwrap balance [1s])",
     "legendFormat": "{{ balance }}"
    }
   ]
  },
  {
   "title": "/api/v0/requests POST Requests per Second",
   "type": "graph",
   "description": "Number of POST requests to /api/v0/requests each second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/api/v0/anchors\" | logfmt | method=\"POST\" and status >= 200 and status < 300 [1s]))",
     "legendFormat": "{{ ip }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/api/v0/anchors\" | logfmt | method=\"POST\" and status >= 200 and status < 300 [1s]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/api/v0/anchors\" | logfmt | method=\"POST\" and status >= 400 and status < 500 [1s]))",
     "legendFormat": "{{ ip }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/api/v0/anchors\" | logfmt | method=\"POST\" and status >= 400 and status < 500 [1s]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (ip) (count_over_time({job=\"cas/access\"} |= \"/api/v0/anchors\" | logfmt | method=\"POST\" and status >= 500 [1s]))",
     "legendFormat": "{{ ip }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} |= \"/api/v0/anchors\" | logfmt | method=\"POST\" and status >= 500 [1s]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Anchor Statuses (Latest)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/events\"} |= \"service=db\" | logfmt [1s]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Anchor Statuses (Latest)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "{job=\"cas/events\"} |= \"service=db\" | logfmt"
    }
   ]
  }
 ]
}