{
 "title": "Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HealthyHostCount (ceramic-dev-gateway)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-dev-gateway/30c5663e092214b7",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount (ceramic-dev-ipfs-gw)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-dev-ipfs-gw-alb-ex/ba27fd6a8f7316a4",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization (ceramic-dev-gateway)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-dev", "ServiceName": "ceramic-dev-gateway" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization (ceramic-dev-gateway)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-dev", "ServiceName": "ceramic-dev-gateway" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization (ceramic-dev-ipfs-gw)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-dev", "ServiceName": "ceramic-dev-ipfs-gw" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization (ceramic-dev-ipfs-gw)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-dev", "ServiceName": "ceramic-dev-ipfs-gw" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests per Origin / Second",
   "type": "graph",
   "description": "Number of requests per second made to the daemon by a given origin",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"http/gateway\"} | regexp \"\\\"request\\\":.*\\\"X-Forwarded-For\\\",\\\"(?P<origin>.+?)\\\"\"[1s])) by (origin)",
     "legendFormat": "{{origin}}"
    },
    {
     "expr": "sum(count_over_time({job=\"legacy-http/gateway\"} | regexp \"\\\"request\\\":.*\\\"X-Forwarded-For\\\",\\\"(?P<origin>.+?)\\\"\"[1s])) by (origin)",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "5XX Responses / Second",
   "type": "graph",
   "description": "Number of 5XX responses returned by the daemon per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"http/gateway\"}|json|response_statusCode >= 500[1s])"
    },
    {
     "expr": "count_over_time({job=\"legacy-http/gateway\"}|json|response_statusCode >= 500[1s])"
    }
   ]
  },
  {
   "title": "Top 10 Gateway Requests per Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({job=\"legacy-http/gateway\"} | json [$__interval])) by (request_url))",
     "legendFormat": "{{request_url}}"
    }
   ]
  },
  {
   "title": "Active DocId Count",
   "type": "graph",
   "description": "docIds that appeared in the /ceramic pubsub every 2 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"legacy-pubsub/gateway\"} | json[2m])) by (message_id)",
     "legendFormat": "{{message_id}}"
    }
   ]
  },
  {
   "title": "Queries in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Queries (i.e. message \"typ\" equals 0) in the /ceramic pubsub topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"legacy-pubsub/gateway\"} | json | message_typ=0 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "queries"
    },
    {
     "expr": "sum(count_over_time({job=\"pubsub/gateway\"} | json | message_typ=0 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "Updates in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Updates (i.e. message \"typ\" equals 1) in the /ceramic pubsub topic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"legacy-pubsub/gateway\"} | json | message_typ=1 [$__interval])) by (job)",
     "legendFormat": "updates"
    },
    {
     "expr": "sum(count_over_time({job=\"pubsub/gateway\"} | json | message_typ=1 [$__interval])) by (job)",
     "legendFormat": "updates"
    }
   ]
  },
  {
   "title": "DocIds in \"/ceramic\" (past 30 days)",
   "type": "graph",
   "description": "Number of docIds seen in the /ceramic pubsub topic in the past 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"agent/docids/gateway\"}[30d])) by (docId)",
     "legendFormat": "unique docId count"
    }
   ]
  },
  {
   "title": "3ids in \"/ceramic\" (past 30 days)",
   "type": "graph",
   "description": "Number of 3ids seen in the /ceramic pubsub topic in the past 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"agent/3ids/gateway\"}[30d])) by (docid)",
     "legendFormat": "unique 3id count"
    }
   ]
  }
 ]
}