{
 "title": "Node",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HealthyHostCount (ceramic-dev-node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-dev-node/783dd13e60640817",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount (ceramic-dev-ipfs-nd)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-dev-ipfs-nd-alb-ex/efa959167dfa8cc6",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization (ceramic-dev-node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-dev", "ServiceName": "ceramic-dev-node" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization (ceramic-dev-node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-dev", "ServiceName": "ceramic-dev-node" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization (ceramic-dev-ipfs-nd)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-dev", "ServiceName": "ceramic-dev-ipfs-nd" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization (ceramic-dev-ipfs-nd)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-dev", "ServiceName": "ceramic-dev-ipfs-nd" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests per Origin / Second",
   "type": "graph",
   "description": "Number of requests per second made to the daemon by a given origin",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [1s])) by (request_remoteAddress)",
     "legendFormat": "{{ request_remoteAddress }}"
    }
   ]
  },
  {
   "title": "5XX Responses / Second",
   "type": "graph",
   "description": "Number of 5XX responses returned by the daemon per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | response_statusCode >= 500[1s])"
    }
   ]
  },
  {
   "title": "Requests per Endpoint / Second",
   "type": "graph",
   "description": "Number of requests per second made to the daemon by endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [1s])) by (request_url)",
     "legendFormat": "{{ request_url }}"
    }
   ]
  },
  {
   "title": "Top 10 Node Requests per Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } }
  },
  {
   "title": "Active DocId Count",
   "type": "graph",
   "description": "docIds that appeared in the /ceramic pubsub every 2 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" [$__interval])) by (message_doc)",
     "legendFormat": "{{ message_doc }}"
    }
   ]
  },
  {
   "title": "Updates in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Updates (i.e. message \"typ\" equals 1) in the /ceramic pubsub topic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=0 [$__interval])) by (job)",
     "legendFormat": "updates"
    }
   ]
  },
  {
   "title": "Queries in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Queries (i.e. message \"typ\" equals 0) in the /ceramic pubsub topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=1 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "Responses in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Queries (i.e. message \"typ\" equals 0) in the /ceramic pubsub topic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=2 and event=\"published\" [$__interval])) by (job)",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "DocIds in \"/ceramic\" (past 30 days)",
   "type": "graph",
   "description": "Number of docIds seen in the /ceramic pubsub topic in the past 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"agent/docids/node\"}[30d])) by (docId)",
     "legendFormat": "unique docId count"
    }
   ]
  },
  {
   "title": "3ids in \"/ceramic\" (past 30 days)",
   "type": "graph",
   "description": "Number of 3ids seen in the /ceramic pubsub topic in the past 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"agent/3ids/node\"}[30d])) by (docid)",
     "legendFormat": "unique 3id count"
    }
   ]
  }
 ]
}