{
 "title": "Anchor Service",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "env", "query": "tnet" }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anchor Worker Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "TaskDefinitionFamily": "ceramic-tnet-cas-anchor" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "default",
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "Active Anchor Worker Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "TaskDefinitionFamily": "ceramic-tnet-cas-anchor" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "default",
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "AnchorWorkerCPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "TaskDefinitionFamily": "ceramic-tnet-cas-anchor" },
     "metricName": "CpuUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "AnchorWorkerMemory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "TaskDefinitionFamily": "ceramic-tnet-cas-anchor" },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( CAS API )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-tnet-cas-alb/60168af4af6042c4",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "RunningTaskCount ( CAS Scheduler )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-scheduler" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "region": "us-east-2",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( CAS Ceramic Node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-tnet-cas-node/b13ee3f0931d2463",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( CAS IPFS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-tnet-cas-ipfs-nd-alb-ex/17d38793357c4ac8",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "/app/ceramic-tnet-cas-ipfs-nd-alb-in/8f7c0390f5d1bc2d",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( CAS API )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPUUtilization_{{ stat }} ({{ ServiceName }})",
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-api" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( CAS Scheduler )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPUUtilization_{{ stat }} ({{ ServiceName }})",
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-scheduler" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( CAS Ceramic Node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-node" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( CAS IPFS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-ipfs-nd" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( CAS API )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "MemoryUtilization_{{ stat }} ({{ ServiceName }}) ",
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-api" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( CAS Scheduler )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "MemoryUtilization_{{ stat }} ({{ ServiceName }})",
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-scheduler" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( CAS Ceramic Node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-node" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( CAS IPFS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-cas", "ServiceName": "ceramic-tnet-cas-ipfs-nd" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Total requests per $bucket",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cas/access\"} [$bucket])",
     "legendFormat": "requests per $bucket"
    }
   ]
  },
  {
   "title": "Responses by Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" | status >= 200 and status < 300 [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" | status >= 300 and status < 400 [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" | status >= 400 and status < 500 [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" | status >= 500 [$bucket]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "GET Requests",
   "type": "graph",
   "description": "Number of GET requests each $bucket",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cas/access\"} |= \"method=GET\" [$bucket])",
     "legendFormat": "requests per $bucket"
    }
   ]
  },
  {
   "title": "POST Requests",
   "type": "graph",
   "description": "Number of POST requests each $bucket",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cas/access\"} |= \"method=POST\" [$bucket])",
     "legendFormat": "requests per $bucket"
    }
   ]
  },
  {
   "title": "Requests per Endpoint  (Top 10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (base_url) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "{{ base_url }}"
    }
   ]
  },
  {
   "title": "Requests per Origin (Top 10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (ip) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Requests per Origin per Endpoint (Top 10)",
   "type": "graph",
   "description": "Requests per origin per endpoint per $bucket, stacked",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (ip, base_url) (count_over_time({job=\"cas/access\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "{{ ip }}, {{ base_url }}"
    }
   ]
  },
  {
   "title": "# of Unique Origins Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (ip) (count_over_time({job=\"cas/access\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "Unique origins / $bucket"
    }
   ]
  },
  { "title": "Anchor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Anchor Statuses (Latest)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/events\"} |= \"service=db\" | logfmt [1s]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Anchor Statuses (Latest)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "{job=\"cas/events\"} |= \"service=db\" | logfmt"
    }
   ]
  },
  {
   "title": "ETH Balance in Gwei",
   "type": "graph",
   "description": "Ethereum balance of anchor service wallet in gwei",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short", "label": "gwei" }
   ],
   "targets": [
    {
     "expr": "sum_over_time({job=\"cas/metrics\"} |= \"walletBalance\" | logfmt | unwrap balance [1s])",
     "legendFormat": "{{ balance }}"
    }
   ]
  },
  { "title": "Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Postgres ReadLatency (ceramic-$env-cas)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "ceramic-$env-cas" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Postgres ReadThroughput (ceramic-$env-cas)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "ceramic-$env-cas" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Postgres CPUUtilization (ceramic-$env-cas)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "ceramic-$env-cas" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Postgres CPUBurstBalance (ceramic-$env-cas)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "ceramic-tnet-cas" },
     "metricName": "BurstBalance",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Postgres CPUCreditUsage (ceramic-$env-cas)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "ceramic-$env-cas" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Postgres CPUCreditBalance (ceramic-$env-cas)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "ceramic-tnet-cas" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}