{
 "title": "Node (External)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HealthyHostCount (ceramic-tnet-ex-node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-tnet-ex-node/fc2f712292600cf4",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount (ceramic-tnet-ex-ipfs-nd)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-tnet-ex-ipfs-nd-alb-ex/8a71ff1e352abdc7",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization (ceramic-tnet-ex-node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-ex", "ServiceName": "ceramic-tnet-ex-node" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization (ceramic-tnet-ex-ipfs-nd)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-ex", "ServiceName": "ceramic-tnet-ex-ipfs-nd" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization (ceramic-tnet-ex-node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-ex", "ServiceName": "ceramic-tnet-ex-node" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization (ceramic-tnet-ex-ipfs-nd)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-tnet-ex", "ServiceName": "ceramic-tnet-ex-ipfs-nd" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count_over_time({app=\"node-external\", job=\"ceramic/http\"} [1s])",
     "legendFormat": "Total requests/second"
    }
   ]
  },
  {
   "title": "Responses by Status",
   "type": "graph",
   "description": "Responses by status / second, stacked",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (response_statusCode) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | response_statusCode >= 200 and response_statusCode < 300 [1s]))",
     "legendFormat": "{{ response_statusCode }}"
    },
    {
     "expr": "sum by (response_statusCode) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | response_statusCode >= 300 and response_statusCode < 400 [1s]))",
     "legendFormat": "{{ response_statusCode }}"
    },
    {
     "expr": "sum by (response_statusCode) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | response_statusCode >= 400 and response_statusCode < 500 [1s]))",
     "legendFormat": "{{ response_statusCode }}"
    },
    {
     "expr": "sum by (response_statusCode) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | response_statusCode >= 500 [1s]))",
     "legendFormat": "{{ response_statusCode }}"
    }
   ]
  },
  {
   "title": "GET Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum by (request_method) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | request_method=\"GET\" [1s]))",
     "legendFormat": "GET requests/second"
    }
   ]
  },
  {
   "title": "POST Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum by (request_method) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | request_method=\"POST\" [1s]))",
     "legendFormat": "POST requests/second"
    }
   ]
  },
  {
   "title": "Requests per Endpoint",
   "type": "graph",
   "description": "Requests per endpoint per second, stacked",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [1s])) by (request_url)",
     "legendFormat": "{{ request_url }}"
    }
   ]
  },
  {
   "title": "Requests per Origin",
   "type": "graph",
   "description": "Requests per origin per second, stacked",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (request_headers_x_forwarded_for) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [1s]))",
     "legendFormat": "{{ request_headers_x_forwarded_for }}"
    }
   ]
  },
  {
   "title": "Requests per Origin per Endpoint",
   "type": "graph",
   "description": "Requests per origin per endpoint per second, stacked",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (request_url, request_headers_x_forwarded_for) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [1s]))",
     "legendFormat": "{{ request_headers_x_forwarded_for }}, {{ request_url }}"
    }
   ]
  },
  {
   "title": "# of Unique Origins Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (request_headers_x_forwarded_for) (count_over_time({app=\"node-external\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [1s])))",
     "legendFormat": "Unique origins / second"
    }
   ]
  }
 ]
}