{
 "title": "PubSub",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "DocIds Active",
   "type": "graph",
   "description": "DocIds logged by this node during this time frame",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (docId) (count_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | docId != \"\" [1s]))",
     "legendFormat": "{{ docId }}"
    }
   ]
  },
  {
   "title": "Cids Active",
   "type": "graph",
   "description": "Cids logged by this node during this time frame",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | cid != \"\" [$__interval])) by (cid)",
     "legendFormat": "{{ cid }}"
    }
   ]
  },
  {
   "title": "# of Unique DocIds Active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (docId) (count_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | docId != \"\" [1s])))",
     "legendFormat": "Unique docIds / second"
    }
   ]
  },
  {
   "title": "# of Unique Cids Active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (cid) (count_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | cid != \"\" [1s])))",
     "legendFormat": "Unique cids / second"
    }
   ]
  },
  {
   "title": "Total Unique DocIds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | docId != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "DocIds"
    }
   ]
  },
  {
   "title": "Total Unique Controllers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | controller != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "Controllers"
    }
   ]
  },
  {
   "title": "Total Unique Schema",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | schema != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "Schema"
    }
   ]
  },
  {
   "title": "Total Unique Families",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | family != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "Families"
    }
   ]
  },
  {
   "title": "Total Unique 3ids",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | threeId != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "3ids"
    }
   ]
  },
  {
   "title": "Total Unique IDX docs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-internal\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | idx != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "IDX docs"
    }
   ]
  },
  {
   "title": "Updates in PubSub Topic",
   "type": "graph",
   "description": "Updates (i.e. message \"typ\" equals 0) in the pubsub topic",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-internal\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=0 [$__interval])) by (job)",
     "legendFormat": "updates"
    }
   ]
  },
  {
   "title": "Queries in PubSub Topic",
   "type": "graph",
   "description": "Queries (i.e. message \"typ\" equals 1 and event is received) in the pubsub topic",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-internal\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=1 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "Responses in PubSub Topic",
   "type": "graph",
   "description": "Queries (i.e. message \"typ\" equals 2 and event is published) in the pubsub topic",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-internal\", job=\"ceramic/pubsub\"} | logfmt | __error__!=\"LogfmtParserErr\" | message_typ=2 and event=\"published\" [$__interval])) by (job)",
     "legendFormat": "responses"
    }
   ]
  }
 ]
}