{
 "title": "Welcome to Ceramic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Your Recently Viewed Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 }
  },
  { "title": "Are We Up?  (selected panels)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Anchor successes/min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cas_anchor_anchor_success[10m]) * 60",
     "legendFormat": "cas anchor success events/min"
    }
   ]
  },
  {
   "title": "CPUUtilization ( CAS IPFS )",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-prod-cas", "ServiceName": "ceramic-prod-cas-ipfs-nd" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "Pubsub Received in ceramic/mainnet ( CAS )",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "update",
     "metricName": "pubsub-prod-cas-rcv-upd",
     "namespace": "pubsub-prod",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "query",
     "metricName": "pubsub-prod-cas-rcv-qry",
     "namespace": "pubsub-prod",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "response",
     "metricName": "pubsub-prod-cas-rcv-rsp",
     "namespace": "pubsub-prod",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "keepalive",
     "metricName": "pubsub-prod-cas-rcv-alv",
     "namespace": "pubsub-prod",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  { "title": "Adoption (selected panels)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Streams by App (Cacao) by Day",
   "type": "graph",
   "description": "total stream updates, grouped by Cacao, in past day",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "last_over_time(sum by (cacao) (increase(agent_stream_total{cacao!=''}[1d] offset -1d))[1d:1d])",
     "legendFormat": "{{cacao}}"
    }
   ]
  },
  {
   "title": "Total Streams by App Family by Day",
   "type": "graph",
   "description": "total stream queries and updates by family in past day (top 10 families)",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, last_over_time(sum by (family)(increase(agent_stream_total{family!='undefined'}[1d]))[1d:1d]))",
     "legendFormat": "{{family}}"
    }
   ]
  },
  { "title": "Product (selected panels)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "READS (Queries) by day",
   "type": "graph",
   "description": "Pubsub QUERY counts by day, vs week prior",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "last_over_time(increase(agent_QUERY_total[1d] offset -1d) [1d:1d])",
     "legendFormat": "this week"
    },
    {
     "expr": "last_over_time(increase(agent_QUERY_total[1d] offset 6d) [1d:1d])\n",
     "legendFormat": "last week"
    }
   ]
  },
  {
   "title": "Version (sample of keepalives) This Week",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(agent_version_sample10_total[5m])) without (job, exported_job, instance)"
    }
   ]
  },
  { "title": "Engineering (selected panels)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Pending, Unprocessed, Reanchored",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cas_anchor_anchorBatch_pendingRequestsCount_sum/cas_anchor_anchorBatch_pendingRequestsCount_count",
     "legendFormat": "Pending"
    },
    {
     "expr": "cas_anchor_anchorBatch_reanchoredCount_sum/cas_anchor_anchorBatch_reanchoredCount_count",
     "legendFormat": "Reanchored"
    },
    {
     "expr": "cas_anchor_anchorBatch_unprocessedRequestCount_sum/cas_anchor_anchorBatch_unprocessedRequestCount_count",
     "legendFormat": "Unprocessed"
    },
    {
     "expr": "cas_anchor_anchorBatch_failedToPublishAnchorCommitCount_sum/cas_anchor_anchorBatch_failedToPublishAnchorCommitCount_count",
     "legendFormat": "Failed to Publish Commit"
    }
   ]
  },
  {
   "title": "Unique Peer Ids per Day",
   "type": "graph",
   "description": "Trailing 24 hr unique peer ids seen by stats agent",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agent_peer_id_uniq_da_total[1d])) without (exported_job, instance, job, version) * 86400\n"
    }
   ]
  }
 ]
}