version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0
  shellcheck: circleci/shellcheck@2.0.0

jobs:
  build-and-update:
    machine: # executor type
      image: ubuntu-1604:201903-01
    parameters:
      ecr-repo-suffix:
        type: string
      dockerfile-path:
        type: string
      ecs-task-family-suffix:
        type: string
    environment:
      REVISION_RANGE: << pipeline.git.base_revision >>..<< pipeline.git.revision >>
    steps:
      - checkout
      - shellcheck/check
      - run:
          name: "Set namespace"
          command: |
            namespace=$(echo $CIRCLE_BRANCH | cut -d '/' -f 2)
            echo "export NAMESPACE=$namespace" >> $BASH_ENV
      - run:
          name: "Check relevant files changed"
          command: |
            if [[ $(git diff $REVISION_RANGE --name-status | grep << parameters.dockerfile-path >>) ]]; then
              echo "Changes to relevant files detected."
            else
              echo "No changes to relevant files detected."
              circleci-agent step halt
            fi
      - aws-ecr/build-and-push-image:
          repo: "ceramic-grafana-${NAMESPACE}-<< parameters.ecr-repo-suffix >>"
          path: << parameters.dockerfile-path >>
          tag: "${CIRCLE_SHA1},${NAMESPACE}"
      - aws-ecs/update-service:
          family: "ceramic-grafana-${NAMESPACE}-<< parameters.ecs-task-family-suffix >>"
          cluster-name: "ceramic-grafana-${NAMESPACE}"
    

workflows:
  build-and-update:
    jobs:
      - build-and-update:
          name: "build-and-update-agent"
          ecr-repo-suffix: "agent"
          dockerfile-path: "agent/"
          ecs-task-family-suffix: "agent"
      - build-and-update:
          name: "build-and-update-loki"
          ecr-repo-suffix: "loki"
          dockerfile-path: "loki/"
          ecs-task-family-suffix: "loki_promtail"
      - build-and-update:
          name: "build-and-update-promtail"
          ecr-repo-suffix: "promtail"
          dockerfile-path: "promtail/"
          ecs-task-family-suffix: "loki_promtail"
