version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2

workflows:
  build-and-push-agent:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: develop

