version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2

workflows:
  build-and-push-agent:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "ceramic-stats-agent"
          tag: "${CIRCLE_SHA1},develop"
          path: "./agent"
          filters:
            branches:
              only: develop

