global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'stats_agent_scraper'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ - '127.0.0.1:9464']
