global:
  scrape_interval:     20s
  scrape_timeout:      20s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'stats_agent_scraper'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '127.0.0.1:9464', '127.0.0.1:8889' ]
  - job_name: 'ipfs_scraper'
    metrics_path: '/debug/metrics/prometheus'
    static_configs:
      - targets: ['10.0.1.76:5011', '10.0.3.203:5011']
