{
 "title": "Anchor Service",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anchor Worker Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-cas", "TaskDefinitionFamily": "ceramic-qa-cas-anchor" },
     "metricName": "CPUUtilization",
     "namespace": "ECS/ContainerInsights",
     "region": "default",
     "statistics": [ "SampleCount" ]
    }
   ]
  },
  {
   "title": "Anchor Worker CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-cas", "TaskDefinitionFamily": "ceramic-qa-cas-anchor" },
     "metricName": "CPUUtilization",
     "namespace": "ECS/ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Anchor Worker Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-anchor" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( CAS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-qa-cas-alb/ea91284a092b4d34",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-qa-cas-alb-internal/38e9be208d120bdf",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( Ceramic Node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-qa-cas-node/8a4f8263301f96a2",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( IPFS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-qa-cas-ipfs-nd-alb-ex/f8aca6b891a222df",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-qa-cas-ipfs-nd-alb-in/f3c3f928fd50ba95",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( CAS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPUUtilization_{{ stat }} ({{ ServiceName }})",
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-api" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    },
    {
     "alias": "CPUUtilization_{{ stat }} ({{ ServiceName }})",
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-anchor" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( Ceramic Node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-node" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( IPFS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-ipfs-nd" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Minimum",
      "Maximum"
     ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( CAS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "MemoryUtilization_{{ stat }} ({{ ServiceName }}) ",
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-api" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    },
    {
     "alias": "MemoryUtilization_{{ stat }} ({{ ServiceName }}) ",
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-anchor" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( Ceramic Node )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-node" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( IPFS )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-cas", "ServiceName": "ceramic-qa-cas-ipfs-nd" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [
      "Average",
      "Maximum",
      "Minimum"
     ]
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Total requests per $bucket",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cas/access\"} [$bucket])",
     "legendFormat": "requests per $bucket"
    }
   ]
  },
  {
   "title": "Responses by Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" | status >= 200 and status < 300 [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" | status >= 300 and status < 400 [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" | status >= 400 and status < 500 [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" | status >= 500 [$bucket]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "GET Requests",
   "type": "graph",
   "description": "Number of GET requests each $bucket",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cas/access\"} |= \"method=GET\" [$bucket])",
     "legendFormat": "requests per $bucket"
    }
   ]
  },
  {
   "title": "POST Requests",
   "type": "graph",
   "description": "Number of POST requests each $bucket",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"cas/access\"} |= \"method=POST\" [$bucket])",
     "legendFormat": "requests per $bucket"
    }
   ]
  },
  {
   "title": "Requests per Endpoint    (Top 10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (base_url) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "{{ base_url }}"
    }
   ]
  },
  {
   "title": "Requests per Origin (Top 10)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (ip) (count_over_time({job=\"cas/access\"} | logfmt | __error__ != \"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Requests per Origin per Endpoint (Top 10)",
   "type": "graph",
   "description": "Requests per origin per endpoint per $bucket, stacked",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (ip, base_url) (count_over_time({job=\"cas/access\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "{{ ip }}, {{ base_url }}"
    }
   ]
  },
  {
   "title": "# of Unique Origins Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (ip) (count_over_time({job=\"cas/access\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "Unique origins / $bucket"
    }
   ]
  },
  { "title": "Anchor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Anchor Statuses (Latest)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"cas/events\"} |= \"service=db\" | logfmt [1s]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Anchor Statuses (Latest)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "{job=\"cas/events\"} |= \"service=db\" | logfmt"
    }
   ]
  },
  {
   "title": "ETH Balance in Gwei",
   "type": "graph",
   "description": "Ethereum balance of anchor service wallet in gwei",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "gwei" }
   ],
   "targets": [
    {
     "expr": "sum_over_time({job=\"cas/metrics\"} |= \"walletBalance\" | logfmt | unwrap balance [1s])",
     "legendFormat": "{{ balance }}"
    }
   ]
  }
 ]
}