{
 "title": "StatsAgentDemos",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "unique stream count by time",
   "type": "graph",
   "description": "Raw number of unique streams seen since the beginning of records",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unique_stream_count_bucket {le=\"500\"}"
    }
   ]
  },
  {
   "title": "Streams By Owner",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner) (rate(BY_FAMILY_total[5m]))"
    }
   ]
  },
  {
   "title": "Streams By Family",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (family) (rate(BY_FAMILY_total[5m]))"
    }
   ]
  },
  {
   "title": "Tips Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(TIP_RECEIVED_total[5m])" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" },
    {}
   ]
  }
 ]
}