{
 "title": "Node (Public)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HealthyHostCount ( ceramic-qa )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-qa-ex-node/bbfff06e72055489",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HealthyHostCount ( ipfs-ceramic-qa )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-qa-ex-ipfs-nd-alb-ex/9f97b72a165ae71c",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "AvailabilityZone": "*",
      "LoadBalancer": "app/ceramic-qa-ex-ipfs-nd-alb-in/ce4c900561b00539",
      "TargetGroup": "*"
     },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( ceramic-qa )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-ex", "ServiceName": "ceramic-qa-ex-node" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPUUtilization ( ipfs-ceramic-qa )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-ex", "ServiceName": "ceramic-qa-ex-ipfs-nd" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( ceramic-qa )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-ex", "ServiceName": "ceramic-qa-ex-node" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "MemoryUtilization ( ipfs-ceramic-qa )",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "ceramic-qa-ex", "ServiceName": "ceramic-qa-ex-ipfs-nd" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "us-east-2",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count_over_time({app=\"node-public\", job=\"ceramic/http\"} [$bucket])",
     "legendFormat": "Total requests/$bucket"
    }
   ]
  },
  {
   "title": "Responses by Status",
   "type": "graph",
   "description": "Responses by status / $bucket, stacked",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 200 and status < 300 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 300 and status < 400 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 400 and status < 500 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    },
    {
     "expr": "sum by (status) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | status >= 500 | __error__!=\"LabelFilterErr\" [$bucket]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "GET Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | method=\"GET\" [$bucket]))",
     "legendFormat": "GET requests/$bucket"
    }
   ]
  },
  {
   "title": "POST Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" | method=\"POST\" [$bucket]))",
     "legendFormat": "POST requests/$bucket"
    }
   ]
  },
  {
   "title": "Requests per Endpoint",
   "type": "graph",
   "description": "Requests per endpoint per $bucket, stacked",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])) by (base_url)",
     "legendFormat": "{{ base_url }}"
    }
   ]
  },
  {
   "title": "Requests per Origin",
   "type": "graph",
   "description": "Requests per origin per $bucket, stacked",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ip) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Requests per Origin per Endpoint",
   "type": "graph",
   "description": "Requests per origin per endpoint per $bucket, stacked",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (ip, base_url) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket]))",
     "legendFormat": "{{ ip }}, {{ base_url }}"
    }
   ]
  },
  {
   "title": "# of Unique Origins Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (ip) (count_over_time({app=\"node-public\", job=\"ceramic/http\"} | logfmt | __error__!=\"LogfmtParserErr\" [$bucket])))",
     "legendFormat": "Unique origins / $bucket"
    }
   ]
  }
 ]
}