{
 "title": "Product",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "StreamIds Active",
   "type": "graph",
   "description": "StreamIds logged by this node during this time frame",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (streamId) (count_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | streamId != \"\" [1s]))",
     "legendFormat": "{{ streamId }}"
    }
   ]
  },
  {
   "title": "Cids Active",
   "type": "graph",
   "description": "Cids logged by this node during this time frame",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | cid != \"\" [$__interval])) by (cid)",
     "legendFormat": "{{ cid }}"
    }
   ]
  },
  {
   "title": "# of Unique StreamIds Active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (streamId) (count_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | streamId != \"\" [1s])))",
     "legendFormat": "Unique streamIds / second"
    }
   ]
  },
  {
   "title": "# of Unique Cids Active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (Value) (sum by (cid) (count_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | cid != \"\" [1s])))",
     "legendFormat": "Unique cids / second"
    }
   ]
  },
  {
   "title": "Total Unique StreamIds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | streamId != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "StreamIds"
    }
   ]
  },
  {
   "title": "Total Unique Controllers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | controller != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "Controllers"
    }
   ]
  },
  {
   "title": "Total Unique Schema",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | schema != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "Schema"
    }
   ]
  },
  {
   "title": "Total Unique Families",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | family != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "Families"
    }
   ]
  },
  {
   "title": "Total Unique 3ids",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | threeId != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "3ids"
    }
   ]
  },
  {
   "title": "Total Unique IDX streams",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum_over_time({app=\"node-private\", job=\"agent\"} | logfmt | __error__!=\"LogfmtParserErr\" | idx != \"\" | totalUnique != \"\" | unwrap totalUnique [$__interval])",
     "legendFormat": "IDX streams"
    }
   ]
  }
 ]
}