{
 "title": "PubSub",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pubsub_topic", "query": "/ceramic/dev-unstable" }
  ]
 },
 "panels": [
  {
   "title": "Received in $pubsub_topic ( gateway )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "update",
     "metricName": "pubsub-qa-gateway-rcv-upd",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "query",
     "metricName": "pubsub-qa-gateway-rcv-qry",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "response",
     "metricName": "pubsub-qa-gateway-rcv-rsp",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "keepalive",
     "metricName": "pubsub-qa-gateway-rcv-alv",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Published in $pubsub_topic ( gateway )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "update",
     "metricName": "pubsub-qa-gateway-snd-upd",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "query",
     "metricName": "pubsub-qa-gateway-snd-qry",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "response",
     "metricName": "pubsub-qa-gateway-snd-rsp",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "keepalive",
     "metricName": "pubsub-qa-gateway-snd-alv",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Received in $pubsub_topic ( private )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "update",
     "metricName": "pubsub-qa-private-rcv-upd",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "query",
     "metricName": "pubsub-qa-private-rcv-qry",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "response",
     "metricName": "pubsub-qa-private-rcv-rsp",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "keepalive",
     "metricName": "pubsub-qa-private-rcv-alv",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Published in $pubsub_topic ( private )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "update",
     "metricName": "pubsub-qa-private-snd-upd",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "query",
     "metricName": "pubsub-qa-private-snd-qry",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "response",
     "metricName": "pubsub-qa-private-snd-rsp",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "keepalive",
     "metricName": "pubsub-qa-public-snd-alv",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Received in $pubsub_topic ( CAS )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "update",
     "metricName": "pubsub-qa-cas-rcv-upd",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "query",
     "metricName": "pubsub-qa-cas-rcv-qry",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "response",
     "metricName": "pubsub-qa-cas-rcv-rsp",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "keepalive",
     "metricName": "pubsub-qa-cas-rcv-alv",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Published in $pubsub_topic ( CAS )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "update",
     "metricName": "pubsub-qa-cas-snd-upd",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "query",
     "metricName": "pubsub-qa-cas-snd-qry",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "response",
     "metricName": "pubsub-qa-cas-snd-rsp",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "keepalive",
     "metricName": "pubsub-qa-cas-snd-alv",
     "namespace": "pubsub-qa",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}