{
 "title": "Ceramic",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Queries per Second in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Queries (where message \"typ\" equals 0) to the /ceramic pubsub topic per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({messageType=\"0\", event=\"received\", job=\"pubsub/gateway\"}[1s])) by (job)",
     "legendFormat": "queries / second"
    }
   ]
  },
  {
   "title": "Updates per Second in /ceramic PubSub Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({messageType=\"1\", job=\"pubsub/node\"}[1s])) by (job)",
     "legendFormat": "updates / second"
    }
   ]
  },
  {
   "title": "DocIds seen in past 5 minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (sum (count_over_time({topic=\"/ceramic\"}[5m])) by (docId))"
    }
   ]
  }
 ]
}