server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: agent/public
  pipeline_stages:
  - regex:
      expression: ts=(?P<timestamp>\d*)
  - timestamp:
      source: timestamp
      format: UnixMs
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-public
      job: agent
      __path__: /logs/ceramic/external/node/stats*.log

- job_name: agent/private
  pipeline_stages:
  - regex:
      expression: ts=(?P<timestamp>\d*)
  - timestamp:
      source: timestamp
      format: UnixMs
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-private
      job: agent
      __path__: /logs/ceramic/internal/node/stats*.log

- job_name: cas/anchor
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/access
      __path__: /logs/cas/anchor/http-access.log
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/events
      __path__: /logs/cas/anchor/events.log
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/metrics
      __path__: /logs/cas/anchor/metrics.log

- job_name: cas/api
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: api
      job: cas/access
      __path__: /logs/cas/server/http-access.log
  - targets:
      - localhost
    labels:
      app: api
      job: cas/events
      __path__: /logs/cas/server/events.log
  - targets:
      - localhost
    labels:
      app: api
      job: cas/metrics
      __path__: /logs/cas/server/metrics.log

- job_name: ceramic/gateway-public
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: gateway-public
      job: ceramic/http
      __path__: /logs/ceramic/external/gateway/http-access.log
  - targets:
      - localhost
    labels:
      app: gateway-public
      job: ceramic/pubsub
      __path__: /logs/ceramic/external/gateway/pubsub.log

- job_name: ceramic/node-public
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-public
      job: ceramic/http
      __path__: /logs/ceramic/external/node/http-access.log
  - targets:
      - localhost
    labels:
      app: node-public
      job: ceramic/pubsub
      __path__: /logs/ceramic/external/node/pubsub.log
  - targets:
      - localhost
    labels:
      app: partners
      job: ceramic/http
      __path__: /logs/ceramic/external/ceramic-*/http-access.log
  - targets:
      - localhost
    labels:
      app: partners
      job: ceramic/pubsub
      __path__: /logs/ceramic/external/ceramic-*/pubsub.log

- job_name: ceramic/node-private
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-private
      job: ceramic/http
      __path__: /logs/ceramic/internal/node/http-access.log
  - targets:
      - localhost
    labels:
      app: node-private
      job: ceramic/pubsub
      __path__: /logs/ceramic/internal/node/pubsub.log
