server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: ceramic/node
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      app: node
      job: ceramic/http
      __path__: /logs/ceramic/internal/node/ceramicdaemon.log
  - targets:
      - localhost
    labels:
      app: node
      job: ceramic/pubsub
      __path__: /logs/ceramic/internal/node/dispatcher.log

- job_name: ceramic/node-public
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-public
      job: ceramic/http
      __path__: /logs/ceramic/public/node/ceramicdaemon.log
  - targets:
      - localhost
    labels:
      app: node-public
      job: ceramic/pubsub
      __path__: /logs/ceramic/public/node/dispatcher.log

- job_name: ceramic/gateway
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      app: gateway
      job: ceramic/http
      __path__: /logs/ceramic/public/gateway/ceramicdaemon.log
  - targets:
      - localhost
    labels:
      app: gateway
      job: ceramic/pubsub
      __path__: /logs/ceramic/public/gateway/dispatcher.log

- job_name: agent/internal
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      app: internal
      job: agent/docids
      __path__: /logs/ceramic/internal/stats-docids.log
  - targets:
      - localhost
    labels:
      app: internal
      job: agent/3ids
      __path__: /logs/ceramic/internal/stats-3ids.log

- job_name: agent/public
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      app: public
      job: agent/docids
      __path__: /logs/ceramic/public/stats-docids.log
  - targets:
      - localhost
    labels:
      app: public
      job: agent/3ids
      __path__: /logs/ceramic/public/stats-3ids.log

- job_name: cas/server
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: server
      job: cas/access
      __path__: /logs/cas/server/access.log
  - targets:
      - localhost
    labels:
      app: server
      job: cas/events
      __path__: /logs/cas/server/events.log
  - targets:
      - localhost
    labels:
      app: server
      job: cas/metrics
      __path__: /logs/cas/server/metrics.log

- job_name: cas/anchor
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/access
      __path__: /logs/cas/anchor/access.log
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/events
      __path__: /logs/cas/anchor/events.log
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/metrics
      __path__: /logs/cas/anchor/metrics.log
