server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: agent/external
  pipeline_stages:
  - regex:
      expression: ts=(?P<timestamp>\d*)
  - timestamp:
      source: timestamp
      format: UnixMs
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-external
      job: agent
      __path__: /logs/ceramic/external/stats*.log

- job_name: agent/internal
  pipeline_stages:
  - regex:
      expression: ts=(?P<timestamp>\d*)
  - timestamp:
      source: timestamp
      format: UnixMs
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-internal
      job: agent
      __path__: /logs/ceramic/internal/stats*.log

- job_name: cas/anchor
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/access
      __path__: /logs/cas/anchor/access.log
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/events
      __path__: /logs/cas/anchor/events.log
  - targets:
      - localhost
    labels:
      app: anchor
      job: cas/metrics
      __path__: /logs/cas/anchor/metrics.log

- job_name: cas/api
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
  static_configs:
  - targets:
      - localhost
    labels:
      app: api
      job: cas/access
      __path__: /logs/cas/api/access.log
  - targets:
      - localhost
    labels:
      app: api
      job: cas/events
      __path__: /logs/cas/api/events.log
  - targets:
      - localhost
    labels:
      app: api
      job: cas/metrics
      __path__: /logs/cas/api/metrics.log

- job_name: ceramic/gateway-external
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      app: gateway-external
      job: ceramic/http
      __path__: /logs/ceramic/external/gateway/ceramicdaemon.log
  - targets:
      - localhost
    labels:
      app: gateway-external
      job: ceramic/pubsub
      __path__: /logs/ceramic/external/gateway/dispatcher.log

- job_name: ceramic/node-external
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-external
      job: ceramic/http
      __path__: /logs/ceramic/external/node/ceramicdaemon.log
  - targets:
      - localhost
    labels:
      app: node-external
      job: ceramic/pubsub
      __path__: /logs/ceramic/external/node/dispatcher.log

- job_name: ceramic/node-internal
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      app: node-internal
      job: ceramic/http
      __path__: /logs/ceramic/internal/node/ceramicdaemon.log
  - targets:
      - localhost
    labels:
      app: node-internal
      job: ceramic/pubsub
      __path__: /logs/ceramic/internal/node/dispatcher.log
