server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: http
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      job: http/node
      __path__: /usr/local/var/log/ceramic/node/ceramicdaemon.log
  - targets:
      - localhost
    labels:
      job: http/gateway
      __path__: /usr/local/var/log/ceramic/gateway/ceramicdaemon.log
  - targets:
      - localhost
    labels:
      job: legacy-http/node
      __path__: /usr/local/var/log/ceramic/ceramicdaemon-node.log
  - targets:
      - localhost
    labels:
      job: legacy-http/gateway
      __path__: /usr/local/var/log/ceramic/ceramicdaemon-gateway.log

- job_name: pubsub
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      job: pubsub/node
      __path__: /usr/local/var/log/ceramic/node/dispatcher.log
  - targets:
      - localhost
    labels:
      job: pubsub/gateway
      __path__: /usr/local/var/log/ceramic/gateway/dispatcher.log
  - targets:
      - localhost
    labels:
      job: legacy-pubsub/node
      __path__: /usr/local/var/log/ceramic/dispatcher-node.log
  - targets:
      - localhost
    labels:
      job: legacy-pubsub/gateway
      __path__: /usr/local/var/log/ceramic/dispatcher-gateway.log

- job_name: agent
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      job: agent/docids/node
      __path__: /usr/local/var/log/ceramic/node/stats-docids.log
  - targets:
      - localhost
    labels:
      job: agent/docids/gateway
      __path__: /usr/local/var/log/ceramic/gateway/stats-docids.log
  - targets:
      - localhost
    labels:
      job: agent/3ids/node
      __path__: /usr/local/var/log/ceramic/node/stats-3ids.log
  - targets:
      - localhost
    labels:
      job: agent/3ids/gateway
      __path__: /usr/local/var/log/ceramic/gateway/stats-3ids.log
