{
 "title": "Default Test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Node Requests per Origin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"http/node\"}[1s])) by (remoteAddress)"
    }
   ]
  },
  {
   "title": "Gateway Requests per Origin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"http/gateway\"}[1s])) by (remoteAddress)"
    }
   ]
  },
  {
   "title": "Node 5XX Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({statusCode=~\"^5.*\", job=\"http/node\"}[1s])) by (timestamp)"
    }
   ]
  },
  {
   "title": "Gateway 5XX Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({statusCode=~\"^5.*\", job=\"http/gateway\"}[1s])) by (timestamp)"
    }
   ]
  },
  {
   "title": "Top 10 Node Requests per Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({job=\"http/node\"}[1s])) by (url))"
    }
   ]
  },
  {
   "title": "Top 10 Gateway Requests per Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({job=\"http/gateway\"}[1s])) by (url))"
    }
   ]
  },
  {
   "title": "Queries per Second in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Queries (where message \"typ\" equals 0) to the /ceramic pubsub topic per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({messageType=\"0\", event=\"received\", job=\"pubsub/gateway\"}[1s])) by (job)",
     "legendFormat": "queries / second"
    }
   ]
  },
  {
   "title": "Updates per Second in /ceramic PubSub Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({messageType=\"1\", job=\"pubsub/node\"}[1s])) by (job)",
     "legendFormat": "updates / second"
    }
   ]
  },
  {
   "title": "Active docIds",
   "type": "graph",
   "description": "docIds that appeared in the /ceramic pubsub in the last 30 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count( sum (count_over_time({topic=\"/ceramic\"}[1s])) by (docId))",
     "legendFormat": "docids"
    }
   ]
  },
  {
   "title": "Unique docIds in /ceramic PubSub topic",
   "type": "graph",
   "description": "Number of docIds seen in the /ceramic pubsub topic in the last 30 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"agent/docids\"}[30m])) by (docid)",
     "legendFormat": "docid count"
    }
   ]
  },
  {
   "title": "Unique 3ids in /ceramic PubSub topic",
   "type": "graph",
   "description": "Number of 3ids seen in the /ceramic pubsub topic in the last 30 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"agent/3ids\"}[30m])) by (docid)",
     "legendFormat": "docid count"
    }
   ]
  }
 ]
}