{
 "title": "Node",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requests per Origin / Second",
   "type": "graph",
   "description": "Number of requests per second made to the daemon by a given origin",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"http\"} | regexp \"\\\"request\\\":.*\\\"X-Forwarded-For\\\",\\\"(?P<origin>.+?)\\\"\"[1s])) by (origin)",
     "legendFormat": "{{origin}}"
    },
    {
     "expr": "sum(count_over_time({job=\"legacy-http/node\"} | regexp \"\\\"request\\\":.*\\\"X-Forwarded-For\\\",\\\"(?P<origin>.+?)\\\"\"[1s])) by (origin)",
     "legendFormat": "{{origin}}"
    }
   ]
  },
  {
   "title": "5XX Responses / Second",
   "type": "graph",
   "description": "Number of 5XX responses returned by the daemon per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"http\"}|json|response_statusCode >= 500[1s])"
    },
    {
     "expr": "count_over_time({job=\"legacy-http/node\"}|json|response_statusCode >= 500[1s])"
    }
   ]
  },
  {
   "title": "Top 10 Node Requests per Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(count_over_time({job=\"http\"}[1s])) by (url))"
    },
    {
     "expr": "topk(10, sum(count_over_time({job=\"legacy-http/node\"}[1s])) by (url))"
    }
   ]
  },
  {
   "title": "Active DocId Count",
   "type": "graph",
   "description": "docIds that appeared in the /ceramic pubsub every 2 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"legacy-pubsub/node\"} | json[2m])) by (message_id)",
     "legendFormat": "{{message_id}}"
    }
   ]
  },
  {
   "title": "Queries in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Queries (i.e. message \"typ\" equals 0) in the /ceramic pubsub topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"legacy-pubsub/node\"} | json | message_typ=0 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "queries"
    },
    {
     "expr": "sum(count_over_time({job=\"pubsub\"} | json | message_typ=0 and event=\"received\" [$__interval])) by (job)",
     "legendFormat": "queries"
    }
   ]
  },
  {
   "title": "Updates in /ceramic PubSub Topic",
   "type": "graph",
   "description": "Updates (i.e. message \"typ\" equals 1) in the /ceramic pubsub topic",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"legacy-pubsub/node\"} | json | message_typ=1 [$__interval])) by (job)",
     "legendFormat": "updates"
    },
    {
     "expr": "sum(count_over_time({job=\"pubsub\"} | json | message_typ=1 [$__interval])) by (job)",
     "legendFormat": "updates"
    }
   ]
  },
  {
   "title": "DocIds in \"/ceramic\" (past 30 days)",
   "type": "graph",
   "description": "Number of docIds seen in the /ceramic pubsub topic in the past 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"agent/docids\"}[30d])) by (docId)",
     "legendFormat": "unique docId count"
    }
   ]
  },
  {
   "title": "3ids in \"/ceramic\" (past 30 days)",
   "type": "graph",
   "description": "Number of 3ids seen in the /ceramic pubsub topic in the past 30 days",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"agent/3ids\"}[30d])) by (docid)",
     "legendFormat": "unique 3id count"
    }
   ]
  }
 ]
}