receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  prometheusremotewrite:
    endpoint: "http://localhost:9201/write"
    tls:
      insecure: true

processors:
  filter/prometheus:
    metrics:
      exclude:
        match_type: strict
        metric_names:
        - cas_server_write_total_tsdb
        - cas_server:write_total_tsdb

  filter/prometheusremotewrite:
    metrics:
      include:
        match_type: strict
        metric_names:
        - cas_server_write_total_tsdb
        - cas_server:write_total_tsdb
        - agent_stream_cum_uniq_sum/agent_stream_cum_uniq_count
        - agent_UPDATE_total
        - agent:UPDATE_total
        - hello_test

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    metrics/prometheus:
      receivers: [otlp]
      processors: [filter/prometheus]
      exporters: [prometheus]
    metrics/prometheusremotewrite:
      receivers: [otlp]
      processors: [filter/prometheusremotewrite]
      exporters: [prometheusremotewrite]

