receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  filter_prometheus:
    metrics:
      exclude:
        match_type: regexp
        metrics_names:
          - ^ts.*
  filter_promscale:
    metrics:
      include:
        match_type: regexp
        metrics_names:
          - ^ts.*

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  promscale:
    endpoint: "http://localhost:9201/write"
    insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    metrics_prometheus:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
    metrics_promscale:
      receivers: [otlp]
      processors: []
      exporters: [promscale]
