receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  prometheusremotewrite:
    endpoint: "http://localhost:9201/write"
    tls:
      insecure: true

processors:
  filter/prometheus:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
        - .*tsdb$
  filter/prometheusremotewrite:
    metrics:
      include:
        match_type: regexp
        metric_names:
        - .*tsdb$

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    metrics/prometheus:
      receivers: [otlp]
      processors: [filter/prometheus]
      exporters: [prometheus]
    metrics/prometheusremotewrite:
      receivers: [otlp]
      processors: [filter/prometheusremotewrite]
      exporters: [prometheusremotewrite]

