receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

processors:
  filter/prometheus:
    metrics:
      exclude:
        match_type: strict
        metric_names:
        - cas_server_write_total_tsdb
        - cas_server:write_total_tsdb

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    metrics/prometheus:
      receivers: [otlp]
      processors: [filter/prometheus]
      exporters: [prometheus]
